apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-api-config
  namespace: maxweather
data:
  OPENWEATHER_BASE_URL: "https://api.openweathermap.org/data/2.5"
  LOG_LEVEL: "INFO"
  APP_NAME: "maxweather-api"
  APP_VERSION: "1.0.0"
